"""Read a run directory's recorded vectors as the canonical 13D relative view.

Shared by scripts/check_sensor_noise.py and scripts/plot_trajectories_3d.py,
both of which compare or draw a run's frames in the world-frame relative view
`[pos(3), vel(3), q_bw(4), omega(3)]` -- the one frame in which every env in
the suite means the same thing by "position". For iss and iss-hcw the recorded
vectors already ARE that view (plus a goal block after it); iss-numerical
records a 21D absolute ECI `state_vector` whose view is a computed transform,
and an `observation_vector` whose layout depends on `observation.mode`.

Which env produced a run comes from its `dataset_card.json`, the same field
the publish path reads (`datasets/hub.py`). A run with no card is an iss run
-- nothing else existed before the card recorded an env -- but a card naming
an env this build does not register is refused rather than guessed at: a
diagnostic read through the wrong env's view returns wrong numbers with a
confident face, which is worse than no answer.

The views compute on the CPU backend. On a GPU, XLA lowers f32 matmuls to
TF32 (a 10-bit mantissa), and the rotations inside a computed view pass
through exactly such ops; that puts ~2e-4 rad of backend rounding on the
attitude it returns, 4x the noncooperative preset's whole attitude sigma, and
a noise check against it fails a correct run. CPU keeps the arithmetic IEEE
f32, and also keeps a read-only diagnostic from taking 75% of a shared card.
`setdefault` before anything imports jax, for the same reasons and with the
same escape hatch as tests/conftest.py: a caller that means to use the GPU
can still say `JAX_PLATFORMS=` and be believed.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

os.environ.setdefault("JAX_PLATFORMS", "cpu")

import jax  # noqa: E402
import jax.numpy as jnp  # noqa: E402
import numpy as np  # noqa: E402

from owm_envs.envs import ENV_REGISTRY, EnvSpec  # noqa: E402
from owm_envs.envs.common.config import BaseTaskConfig  # noqa: E402
from owm_envs.envs.common.layout import VIEW_DIM  # noqa: E402


def run_env(run_dir: Path) -> tuple[EnvSpec, BaseTaskConfig]:
    """The env a run was generated with, and its as-run config."""
    card = run_dir / "dataset_card.json"
    name = json.loads(card.read_text()).get("env", "iss") if card.is_file() else "iss"
    if name not in ENV_REGISTRY:
        raise SystemExit(
            f"{run_dir} was generated by env '{name}', which this build of owm-envs "
            "does not register; reading its vectors through another env's layout "
            "would silently misread them."
        )
    spec = ENV_REGISTRY[name]
    return spec, spec.config_cls.from_yaml(run_dir / "env_config.yaml")


def state_views(spec: EnvSpec, states: np.ndarray) -> np.ndarray:
    """(N, state_dim) true states -> their (N, 13) canonical relative views.

    `spec.view` is the registry's own state -> view map: a plain slice for the
    envs whose state is the view, and the world-frame derivation for one whose
    state is absolute. f64 in and out, so an ECI-magnitude position loses
    nothing on its way to a metre-scale relative one.
    """
    return np.asarray(jax.vmap(spec.view)(jnp.asarray(states, jnp.float64)))


def observed_views(spec: EnvSpec, cfg: BaseTaskConfig, obs: np.ndarray) -> np.ndarray:
    """(N, obs_dim) recorded observations -> the (N, 13) measured views inside.

    An env without `make_observe` records its (measured) state directly, so
    the view is the first 13 columns and anything past them is the goal-error
    block. An env with observation modes records what the mode says: under
    "relative" that is the view behind the layout's epoch prefix. The absolute
    modes store ECI magnitudes at float32, whose ~0.5 m grain swamps a
    metre-scale relative quantity, so there is no honest way to read the
    measured view back out of them.
    """
    if spec.make_observe is None:
        return obs[:, :VIEW_DIM]
    mode = cfg.observation.mode
    if mode != "relative":
        raise SystemExit(
            f"this run recorded observations in mode '{mode}', which does not "
            "carry the measured relative view; only mode 'relative' (or an env "
            "that records its state directly) can be read this way."
        )
    start = spec.layout.epoch.stop
    return obs[:, start:start + VIEW_DIM]
